std_msgs/Header header
  
float32 f_x
float32 f_y
float32 f_z
uint8 u_invalid_flags
float32 f_range_rate
float32 f_range_rate_std
int8 s_rcs
uint16 u_measurement_id
uint8 u_positive_predictive_value
uint8 u_classification
uint8 u_multi_target_probability
uint16 u_object_id
uint8 u_ambiguity_flag
uint16 u_sort_index

# std_msgs/Header header
  
# float32 f_x
# float32 f_y
# float32 f_z
# uint8 u_InvalidFlags
# float32 f_RangeRate
# float32 f_RangeRateSTD
# int8 s_RCS
# uint16 u_MeasurementID
# uint8 u_PositivePredictiveValue
# uint8 u_Classification
# uint8 u_MultiTargetProbability
# uint16 u_ObjectID
# uint8 u_AmbiguityFlag
# uint16 u_SortIndex