uint16 service_id
uint16 method_id
uint32 data_length
uint16 client_id
uint16 session_id
uint8 protocol_version
uint8 interface_version
uint8 message_type
uint8 return_code
uint64 crc
uint32 length
uint32 sqc
uint32 data_id
uint32 timestamp_nanoseconds
uint32 timestamp_seconds
uint8 timestamp_sync_status
uint32 event_data_qualifier
uint8 extended_qualifier
uint16 origin_invalid_flags
float32 origin_xpos
float32 origin_xstd
float32 origin_ypos
float32 origin_ystd
float32 origin_zpos
float32 origin_zstd
float32 origin_roll
float32 origin_rollstd
float32 origin_pitch
float32 origin_pitchstd
float32 origin_yaw
float32 origin_yawstd
uint8 list_invalid_flags
Detections[] detection_array
float32 list_rad_vel_domain_min
float32 list_rad_vel_domain_max
uint32 list_num_of_detections
float32 aln_azimuth_correction
float32 aln_elevation_correction
uint8 aln_status

# uint16 serviceID
# uint16 MethodID
# uint32 data_length
# uint16 clientID
# uint16 sessionID
# uint8 protocol_version
# uint8 interface_version
# uint8 message_type
# uint8 return_code
# uint64 CRC
# uint32 Length
# uint32 SQC
# uint32 DataID
# uint32 Timestamp_Nanoseconds
# uint32 Timestamp_Seconds
# uint8 Timestamp_SyncStatus
# uint32 EventDataQualifier
# uint8 ExtendedQualifier
# uint16 Origin_InvalidFlags
# float32 Origin_Xpos
# float32 Origin_Xstd
# float32 Origin_Ypos
# float32 Origin_Ystd
# float32 Origin_Zpos
# float32 Origin_Zstd
# float32 Origin_Roll
# float32 Origin_Rollstd
# float32 Origin_Pitch
# float32 Origin_Pitchstd
# float32 Origin_Yaw
# float32 Origin_Yawstd
# uint8 List_InvalidFlags
# detections[] detection_array
# float32 List_RadVelDomain_Min
# float32 List_RadVelDomain_Max
# uint32 List_NumOfDetections
# float32 Aln_AzimuthCorrection
# float32 Aln_ElevationCorrection
# uint8 Aln_Status