uint16 service_id
uint16 method_id
uint32 data_length
uint16 client_id
uint16 session_id
uint8 protocol_version
uint8 interface_version
uint8 message_type
uint8 return_code
uint64 crc
uint32 length
uint32 sqc
uint32 data_id
uint32 timestamp_nanoseconds
uint32 timestamp_seconds
uint8 timestamp_sync_status
uint32 event_data_qualifier
uint8 extended_qualifier
uint8 object_list_num_of_objects
Objects[] object_array

# uint16 serviceID
# uint16 MethodID
# uint32 data_length
# uint16 clientID
# uint16 sessionID
# uint8 protocol_version
# uint8 interface_version
# uint8 message_type
# uint8 return_code
# uint64 CRC
# uint32 Length
# uint32 SQC
# uint32 DataID
# uint32 Timestamp_Nanoseconds
# uint32 Timestamp_Seconds
# uint8 Timestamp_SyncStatus
# uint32 EventDataQualifier
# uint8 ExtendedQualifier
# uint8 ObjectList_NumOfObjects
# objects[] object_array
