std_msgs/Header header

float32 longitudinal
float32 lateral
float32 vertical
float32 yaw
float32 pitch
uint8 plug_orientation
float32 length
float32 width
float32 height
float32 wheelbase
uint16 maximum_distance
uint8 frequency_slot
uint8 cycle_time
uint8 time_slot
uint8 hcc
uint8 powersave_standstill
uint32 sensor_ip_address_0
uint32 sensor_ip_address_1
uint8 configuration_counter
uint8 status_longitudinal_velocity
uint8 status_longitudinal_acceleration
uint8 status_lateral_acceleration
uint8 status_yaw_rate
uint8 status_steering_angle
uint8 status_driving_direction
uint8 status_characteristic_speed
uint8 status_radar

uint32 timestamp_nanoseconds
uint32 timestamp_seconds
uint8 timestamp_sync_status
uint8 sw_version_major
uint8 sw_version_minor
uint8 sw_version_patch

uint8 status_voltage_status
uint8 status_temperature_status
uint8 status_blockage_status

# std_msgs/Header header

# float32 Longitudinal
# float32 Lateral
# float32 Vertical
# float32 Yaw
# float32 Pitch
# uint8 PlugOrientation
# float32 Length
# float32 Width
# float32 Height
# float32 Wheelbase
# uint16 MaximumDistance
# uint8 FrequencySlot
# uint8 CycleTime
# uint8 TimeSlot
# uint8 HCC
# uint8 Powersave_Standstill
# uint32 SensorIPAddress_0
# uint32 SensorIPAddress_1
# uint8 Configuration_counter
# uint8 Status_LongitudinalVelocity
# uint8 Status_LongitudinalAcceleration
# uint8 Status_LateralAcceleration
# uint8 Status_YawRate
# uint8 Status_SteeringAngle
# uint8 Status_DrivingDirection
# uint8 Status_CharacteristicSpeed
# uint8 Status_Radar

# uint32 Timestamp_Nanoseconds
# uint32 Timestamp_Seconds
# uint8 Timestamp_SyncStatus
# uint8 SWVersion_Major
# uint8 SWVersion_Minor
# uint8 SWVersion_Patch

# uint8 Status_VoltageStatus
# uint8 Status_TemperatureStatus
# uint8 Status_BlockageStatus